pull_request_rules:
  - name: Automatic update of outdated branches with merge strategy
    conditions:
      - -conflict
      - -draft
      - label="automerge-update"
    actions:
      update:
        bot_account: kelvin-olaiya
  - name: Automatic update of outdated branches with rebase strategy
    conditions:
      - -conflict
      - -draft
      - label="autorebase-update"
    actions:
      rebase:
        bot_account: kelvin-olaiya
  - name: Ask PR author to kindly resolve conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: |
          Hey @{{author}}, unfortunately this PR has some conflicts... :disappointed:
          Could you please fix them? Thks :kissing_heart:
queue_rules:
  - name: Rebase Renovate PRs
    queue_conditions:
      - author=renovate[bot]
      - label=dependencies
      - -conflict
      - -draft
    merge_conditions:
      - or:
          - check-success=success
          - check-skipped=success
          - check-neutral=success
    batch_size: 5
    speculative_checks: 5
    batch_max_wait_time: "3 min"
    queue_branch_prefix: mergify/renovate/
    merge_method: rebase
