pull_request_rules:
  - name: Automatic update of outdated branches with merge strategy
    conditions:
      - -conflict
      - -draft
      - label="automerge-update"
    actions:
      update:
        bot_account: kelvin-olaiya
  - name: Automatic update of outdated branches with rebase strategy
    conditions:
      - -conflict
      - -draft
      - label="autorebase-update"
    actions:
      rebase:
        bot_account: kelvin-olaiya
  - name: Ask PR author to kindly resolve conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: |
          Hey @{{author}}, unfortunately this PR has some conflicts... :disappointed:
          Could you please fix them? Thks :kissing_heart:
  - name: Rebase new updates on passing CI
    conditions:
      - and:
          - author=renovate[bot]
          - or:
              - check-success=success
              - check-skipped=success
              - check-neutral=success
          - label=dependecies
          - -conflict
          - -draft
    actions:
      merge:
        method: rebase
