pull_request_rules:
  - name: Automatic update of outdated branches with merge strategy
    conditions:
      - -conflict
      - -draft
      - label="automerge-update"
    actions:
      update:
  - name: Automatic update of outdated branches with rebase strategy
    conditions:
      - -conflict
      - -draft
      - label="autorebase-update"
    actions:
      rebase:
  - name: Ask PR author to kindly resolve conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: |
          Hey @{{author}}, unfortunately this PRs has some conflicts... :disappointed:
          Could you please fix them? Thks :kissing_heart:
